application: easyphotos-1000
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: /favicon.ico
  upload: favicon\.ico

- url: .*
  script: app.py

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
- url: /env
  static_dir: /env
- url: /env/lib/python.27/site-packages
  static_dir: site-packages

libraries:
- name: webapp2
  version: "2.5.2"
